### ISSUE TITLE
Homekit TV Category Support

### ISSUE THREAD

**Issue by ezadoo** [SeydX/homebridge-bravia-tv#14]
Apple announced HomeKit Support for TVs, with Airplay 2 and other features to control the sources, change the channels and turn-on/off. As the Developer Uptdate to iOS 12.2 shows, it‘s already supported by this update and some developers showing a working beta (e.g. on Twitter).

So, please add support for the TV category and the TV profile in Home-App, with support for the integrated Apple TV Remote in the Controlcenter.
Have a look here: https://twitter.com/khaost/status/1088677113106903040?s=21

**Comment by arnif** [comment]
https://github.com/arnif/homebridge-sony-television

**Comment by SeydX** [comment]
@ezadoo 
HomeKit TV version: https://github.com/SeydX/homebridge-bravia-tvos
