### ISSUE TITLE
Homekit iOS 12.2 TV support ?

### ISSUE THREAD

**Issue by DannyRuchtie** [SeydX/homebridge-bravia-tv#18]
I was wondering if you guys already are working on TV accessories support for the upcoming iOS 12.2.
I saw the work of Khoas Tian for webos TV's: https://github.com/merdok/homebridge-webos-tv/blob/master/index.js

**Comment by seydx** [comment]
Already done

https://github.com/SeydX/homebridge-bravia-tvos
