### ISSUE TITLE
Why is MaxVolume set to 35

### ISSUE THREAD

**Issue by promiseofcake** [SeydX/homebridge-bravia-tv#19]
Why are maxVolume and lastVolume initialized to `35` in [accessory.js](https://github.com/SeydX/homebridge-bravia-tv/blob/48f6000a6dd8f8ed2a5794e6eae35c1cff3d1d32/src/accessory.js#L189-L190)

```js
    accessory.context.lastvolume = 35;
    accessory.context.maxvolume = 35;
```

I cannot raise the volume over that maximum and wondering is this is for compatibility or otherwise.

Thanks.

**Comment by mixtly87** [comment]
If I set the maxvolume to ie 50:
`accessory.context.maxvolume = 50;`
nothing changes. I restarted the homebridge but 35 is still the maximum volume. Is there a way to make homebridge-bravia-tv aware of the change? Should it be recompiled somehow?
