### ISSUE TITLE
Not appearing in Home app or 3rd parties

### ISSUE THREAD

**Issue by XusBadia** [SeydX/homebridge-bravia-tv#3]
I've followed the instructions to prepare the TV for the plugin, I've installed and changed the config.json, but the TV is not showing up on my iPhone.

Here's whatmy config.json looks like:
{
  "bridge" : {
    "username" : "...",
    "name" : "...",
    "pin" : "...",
    "port" : ...
  },
  "accessories" : [
    {
      "name" : "Pi Temp",
      "accessory" : "RaspberryPiTemperature"
    }
  ],
  "platforms" : [
    {
      "psk" : "0705",
      "name" : "TV",
      "ipadress" : "192.168.1.59",
      "platform" : "BraviaTV"
    },
    {
      "platform" : "BelkinWeMo",
      "name" : "WeMo Platform"
    }
  ]
}

Any ideas on what I may be forgetting?

Thanks!

**Comment by XusBadia** [comment]
Here's the log:
May  9 18:00:23 raspberrypi homebridge[26518]:     ┌────────────┐
May  9 18:00:23 raspberrypi homebridge[26518]:     │ 031-45-154 │
May  9 18:00:23 raspberrypi homebridge[26518]:     └────────────┘
May  9 18:00:23 raspberrypi homebridge[26518]:                        
May  9 18:00:23 raspberrypi homebridge[26518]: [2018-5-9 18:00:23] Homebridge is running on port 51826.
May  9 18:00:23 raspberrypi homebridge[26518]: [2018-5-9 18:00:23] [WeMo Platform] Online: Nespresso [B4750E72DB54]
May  9 18:00:37 raspberrypi dhcpcd[328]: wlan0: Router Advertisement from fe80::d67b:b0ff:fe51:e75c
May  9 18:00:37 raspberrypi dhcpcd[328]: wlan0: requesting DHCPv6 information
May  9 18:00:54 raspberrypi dhcpcd[328]: wlan0: Router Advertisement from fe80::d67b:b0ff:fe51:e75c
May  9 18:00:54 raspberrypi dhcpcd[328]: wlan0: requesting DHCPv6 information
May  9 18:01:24 raspberrypi dhcpcd[328]: wlan0: Router Advertisement from fe80::d67b:b0ff:fe51:e75c
May  9 18:01:25 raspberrypi dhcpcd[328]: wlan0: requesting DHCPv6 information

**Comment by XusBadia** [comment]
It seems like I got it working. I stopped the daemon and run homebridge with the "homebridge" command, so now it appears in the Home app. I'll see if I can get everything working. Thanks!

**Comment by SeydX** [comment]
Sounds good, im closing this issue then, feel Free to Open again if you got problems
